apiVersion: v1
kind: Service
metadata:
  name: lms-frontend-service
spec:
  type: NodePort #  test the local machine (NodePort) or use LoadBalancer for cloud providers
  selector:
    app: lms-frontend
  ports:
    - protocol: TCP
      port: 80       # port in a service
      targetPort: 80 #port of the container (frontend)
      nodePort: 30080 # look for the frontend service in the browser using http://localhost:30080